### PR TITLE
Update to Django 1.10

### PR DESCRIPTION
**Pull request by JelteF**

### CODE REVIEW

**Comment by dwightgunning** [comment]
@JelteF Django is now up to 1.11.5 so this PR is probably now stale. I'd propose we close this PR and create a new Issue so that we can plan in the relevant work. Agree?

**Comment by JelteF** [comment]
I think this one can still be merged if the conflict is solved (which seems like it should be fairly straight forward). Also I think 1.10 is an LTS release, so it would still make sense to migrate it from 1.9.

**Comment by JelteF** [comment]
As far as reviewing goes, I think it would be best if you could try and run it with the new dependencies

**Comment by JelteF** [comment]
Oh, I see I was wrong. 1.11 is the LTS release. However, I still think it makes sense to merge this as it would make migrating to 1.11 easier as part of the work is already done.

**Comment by dwightgunning** [comment]
That's fine. I can run with it from here. Thx.

**Comment by dwightgunning** [comment]
This will be superseded by #23. Closing without merge.

**Pull request closed without merging**
